config/routes.rb
Rails.application.routes.draw do

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]

  get '/comments/:id/cancel_edit_comment', to: 'comments#cancel_edit', as: :cancel_edit_comment
  get '/comments/cancel_new_comment', to: 'comments#cancel_new', as: :cancel_new_comment
  #get '/proofs/:id/cancel_new_comment', to: 'proofs#cancel_new', as: :cancel_new_comment


  resources :topics do
    member do
      get :problems
      get :proofs
      get :followers
      get :log
      get :description
    end

    collection do
      get :search
    end
  end

  resources :proofs do
    member do
      get :log
      get :comments
    end
  end

  get '/proofs/:id/cancel_edit', to: 'proofs#cancel_edit', as: :cancel_edit
  get 'users/show'

  get 'static_pages/landing'
  get '/about', to: 'static_pages#about', as: :about
  get '/contact_us', to: 'static_pages#contact', as: :contact
  get '/tour', to: 'static_pages#tour', as: :tour

  get '/help', to: 'help_center#help', as: :help

  ################## help center categories #####################

  get '/help/:category', to: 'help_center#category', as: :help_center_category
=begin
  get '/help/problems', to: 'help_center#problems', as: :help_category_problems
  get '/help/reputation', to: 'help_center#reputation', as: :help_category_reputation
  get '/help/proofs', to: 'help_center#proofs', as: :help_category_proofs
  get '/help/account', to: 'help_center#account', as: :help_category_account
  get '/help/privileges', to: 'help_center#privileges', as: :help_category_privileges
=end
  ################ help center articles ####################

  get '/help/:category/:article', to: 'help_center#article', as: :help_center_article
=begin
  #get '/help/priviliges/:id', to: 'help_center#priviliges', as: :priviliges
  get '/help/mathjax_cheatsheet', to: 'help_center#mathjax_cheatsheet', as: :mathjax_cheatsheet
  get '/help/topics', to: 'help_center#on_topics', as: :on_topics
  get '/help/good-problems', to: 'help_center#good_problems', as: :good_problems
  get '/help/problem-feed', to: 'help_center#on_problem_feed', as: :on_problem_feed
  get '/help/expected-behavior', to: 'help_center#expected_behavior', as: :expected_behavior
  get '/help/editing-posts', to: 'help_center#editing_posts', as: :editing_posts
  get '/help/creating-topics', to: 'help_center#creating_topics', as: :creating_topics
  get '/help/deleting-posts', to: 'help_center#deleting_posts', as: :deleting_posts
  #get '/help/reputation', to: 'help_center#reputation', as: :reputation
  get '/help/badges', to: 'help_center#badges', as: :badges
=end

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
			root 'problems#feed'
		end
		
		unauthenticated do
			root 'static_pages#landing'
		end
  end
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :problems
      get :comments
      get :problem_edits
      get :problems_following
      get :proofs
      get :activity
      get :followers
      get :following
      get :topic_edits
      get :topics_following
      post :follow
      delete :unfollow
      patch :update_image
    end
  end

  resources :reports, only: [:new, :create, :update, :index, :show] do
    collection do
      get 'reserved'
      get 'history'
      get 'users'
      get 'help'
    end

    member do
      get 'close'
      put 'close'
      put 'decline'
      put 'reserve'
      delete 'unreserve'
    end
  end

  resources :versions, only: [:show]
  resources :problems do
    member do
      get :followers
      get :comments
    end
  end
  get "/feed", to: "problems#feed", as: :feed

  get '/problems/:id/log', to: 'problems#log', as: :problem_log
  resources :images, only: [:create, :destroy]
  put '/vote', to: 'users#vote', as: :vote

  post '/problems/:id/bookmark', to: 'problems#bookmark', as: :problem_bookmark
	delete '/problems/:id/unbookmark', to: 'problems#unbookmark', as: :problem_unbookmark

  post '/topics/:id/follow', to: 'topics#follow', as: :topic_follow
	delete '/topics/:id/unfollow', to: 'topics#unfollow', as: :topic_unfollow

  resources :conversations do
    resources :messages
  end

  post '/conversations/:id/mark_as_read', to: 'conversations#mark_as_read', as: :mark_as_read_message
  post '/conversations/mark_all_as_read', to: 'conversations#mark_all_as_read', as: :mark_all_as_read_messages
 
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end

  get '/search', to: "search#search", as: :search

  get '/main_search', to: 'users#main_search', as: :main_search
  mathjax 'mathjax'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  before_destroy :update_activities

  has_many :user_relationships, class_name: "TopicFollowing", :dependent => :destroy
  has_many :followers, through: :user_relationships, source: :user
  has_many :problem_topics
  has_many :problems, through: :problem_topics, dependent: :destroy
  has_many :version_topics
  has_many :versions, -> { order(created_at: :desc) }, 
             as: :versioned, dependent: :destroy
  has_many :topic_images
  has_many :images, through: :topic_images, :dependent => :destroy

  has_many :notifications, as: :notifiable, :dependent => :destroy
  has_many :activities, as: :acted_on, :dependent => :destroy


  before_save { self.name = name.downcase.titleize }
  validates :name, presence: true, length: { minimum: 3, maximum: 25 },
                   uniqueness: true
  validates :description, length: { maximum: 10000 }
  validates :cached_problems_count, presence: true, 
                                    numericality: {only_integer: true,
                                      greater_than_or_equal_to: 0 }

  validates_format_of :name, :with => /\A[A-Za-z\d\s]*\z/,
    :message => "can only contain a-z, A-Z, 0-9, ' '"

  scope :active, -> { where(deleted_on: nil) }

  def save_new(images, user)
    begin
      ActiveRecord::Base.transaction do
        self.save!
        Version.create!(versioned: self, 
                      version_number: 1, 
                      user_id: user.id, title: self.name,
                      content: self.description, description: "Topic Created")

        Image.add_new_images!(self, images, user)
      end

    rescue ActiveRecord::RecordInvalid => exception
      return { exception: exception }
    rescue Exceptions::ImagesFieldInvalid => exception
      return { exception: exception }
    end

    return { }
  end

  def save_edit(images, version_description, user)
    begin
      ActiveRecord::Base.transaction do
        self.save!
        Version.create!(versioned: self, 
                      version_number: Version.next_version_number(self),          #self.next_version_number
                      user_id: user.id, title: self.name,
                      content: self.description, description: version_description)

        Image.add_new_images!(self, images, user)
      end

    rescue ActiveRecord::RecordInvalid => exception
      return { exception: exception }
    rescue Exceptions::ImagesFieldInvalid => exception
      return { exception: exception }
    end

    return { }
  end

  def next_version_number
    versions.order(:created_at).last.version_number + 1
  end


  # Returns a topic's problem feed.
  def self.feed(options = {sorter: "cached_problems_count"})
    options[:sorter] = "cached_problems_count" if options[:sorter].nil?
    order = "DESC"
    order = "ASC" if options[:sorter] == "name"
    if !options[:search_filter].blank?
      Topic.where("name LIKE ?", "%#{options[:search_filter]}%").active.
        order("#{options[:sorter]} #{order}")
    else
      Topic.all.active.order("#{options[:sorter]} #{order}")
    end
  end

  def proofs
    problem_ids = "SELECT problem_id FROM problem_topics
                     WHERE  topic_id = #{id}"
    Proof.where("problem_id IN (#{problem_ids})")
  end

  def soft_deleted?
    self.deleted_on.nil? ? false : true
  end

  def trending_problem 
    n = 1
    problems = self.problems.where('problems.created_at >= ?', n.week.ago)
    while problems.count == 0
      n += 1
      problems = self.problems.where('problems.created_at >= ?', n.week.ago)
    end

    problems.where(cached_votes_score: problems.maximum('cached_votes_score')).first
  end

  def featured_problem
    @featured_problem ||= trending_problem
  end

  def related_topics
    Topic.select("topics.id, topics.name, count(problem_topics.topic_id) as count").where.not(id: self.id).joins(:problem_topics).where(problem_topics: { problem_id: problems }).group("problem_topics.topic_id").order("count DESC").limit(5)
  end

  def self.search(pattern)
    Topic.select("name AS label", "id AS id", "cached_problems_count AS cached_problems_count").where("name LIKE ?", pattern).limit(5)

  end

  private

    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, :active_topic, only: [:show, :edit, :update, :destroy, :problems, 
                                   :followers, :follow, :unfollow, 
                                   :log, :proofs, :description]

  def follow
    current_user.follow @topic
  end

  def unfollow
    current_user.unfollow @topic
  end

  # GET /topics
  # GET /topics.json
  def index
    respond_to do |format|
      format.html {
        @topics = Topic.feed
      }

      format.json { 
        data = Topic.where("name LIKE :name", { name: "#{params[:term]}%" }).active.map {|t| t.name}
        render json: { suggestions: data, success: true }
      }

      format.js {
        @topics = Topic.feed({sorter: params[:sorter], search_filter: params[:search_filter]})
      }
    end
  end

  def search
    respond_to do |format|
      format.json {
        @suggestions = Topic.search("%#{params[:query]}%")
        render json: { suggestions: @suggestions }
      }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @new_images = ""
  end

  # GET /topics/1/edit
  def edit
    @new_images = ""
  end

  def problems
    @problems = @topic.problems.order(created_at: :desc)
  end

  def followers
    @followers = @topic.followers.order(created_at: :desc)
  end

  def log
    @versions = @topic.versions.order(created_at: :desc)
  end

  def proofs
    @proofs = @topic.proofs.order(created_at: :desc)
  end

  def description
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @new_images = topic_images_params["images"]
    images_array = @new_images.split(",")
    @exception = @topic.save_new(images_array, current_user)[:exception]

    respond_to do |format|
      if !@exception
        #Notify followers when you create a topic
        Notifications::Sender::SendNotifications.new(notification_type: :new_topic,
                                                     actor: current_user,
                                                     resource: @topic).call

        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    @topic.update_attributes(topic_params)
    @new_images = topic_images_params["images"]
    images_array = @new_images.split(",")
    version_description = params["version"]["description"]

    @exception = @topic.save_edit(images_array, version_description, current_user)[:exception]

    respond_to do |format|
      if !@exception

        Notifications::Sender::SendNotifications.new(notification_type: :updated_topic,
                                                     actor: current_user,
                                                     resource: @topic).call

        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      if params[:id].is_integer?
        @topic = Topic.find(params[:id])
      else
        @topic = Topic.find_by(name: params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end

    def topic_images_params
      params.require(:topic).permit(:images)
    end

    # Confirms topic was not soft deleted
    def active_topic
      if Topic.find(params[:id]).soft_deleted?
        flash[:alert] = "Action not authorized"
        redirect_to root_url
      end
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def more_than_two_related_topics?
    (@related_topics = @topic.related_topics).count > 2
  end
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic_description.html.erb
<div class="boxedtitle add-problem-title mb-40"><h2>Description</h2></div>
<!-- Blog Post -->
<div class="col-md-12 blog-post-single wow fadeIn" data-wow-delay=".1s" data-wow-duration="2s">
          
  <!-- Title -->
  <h2 class="post-title font-weight-600 pt-20 problem-desc mb-30 "><%= @topic.name %></h2>
          
  <div class="mb-40 mt-20 blog-post-content">
    <%= sanitize @topic.description %>

    <%= report_button @topic %>
    <% if signed_in? %>
      <%= link_to edit_topic_path(@topic.id), class: 'btn-text btn-small, float-right small-padding mr-5' do %>
        <span class="proof-edit"><i class="mr-5 glyphicon glyphicon-edit"></i>Edit</span>
      <% end %>
    <% end %>
  </div>
</div><!-- / .blog-post-single -->

app/views/topics/description.js.erb
$('.tab-content .tab-list-content').html("<%= escape_javascript render(:partial => '/topics/topic_description', locals: { :@topic => @topic } ) %>");
$content = $('.tab-content');
  setTimeout(function() {
	  MathJax.Hub.Queue(["Typeset", MathJax.Hub, $content[0]]);
} ,500);

app/views/topics/follow.js.erb
$('#topic-follow-<%=@topic.id%>').html("<a href='<%=topic_unfollow_path(@topic.id)%>' data-remote='true' data-method='delete'><button class='" + $('#topic-follow-<%=@topic.id%>').data("class") + "'>Following</button></a>");

$('#topic-<%=@topic.id%>-followers').text('<%= pluralize(@topic.followers.count, "Follower") %>');

if ($("#followers-stat-val").length > 0) {
  $("#followers-stat-val").text('<%= @topic.followers.count %>');
}

if ($(".tag-list-container .tag:contains(<%=@topic.name%>)").length > 0) {
  $(".tag-list-container .tag:contains(<%=@topic.name%>)").attr('data-id', "<%=@topic.id%>");
}

app/views/topics/followers.js.erb
<% if @followers.count > 0 %>
  $('.tab-content .tab-list-content').append("<section class='ft-boxed-hover' id='user-items'><div class='row'><ul></ul></div></section>");
  $('.tab-content .tab-list-content ul').html("<%= escape_javascript render(:partial => '/shared/items/user_item', collection: @followers, as: :user ) %>");
<% else %>
  $(".tab-content .tab-list-content").html("<%= no_results_content('users') %>");
<% end %>

$('.tab-content .tab-list-content').prepend("<div class='boxedtitle add-problem-title mb-40'><h2>Followers (<%=@followers.count%>)</h2></div>");

$('.spinner').slideUp(1000);

app/views/topics/index.html.erb
<%= render 'layouts/sticky_nav' %>

<div class="section container-fluid blog-classic">
  <div class="row">
    <div class="col-md-12">
      <div class="mh-auto ft-tabs">
        <div class="row">
            
          <%= render 'shared/main_site_tabs' %>

          <!-- Tabs Content -->
          <div class="col-lg-8 no-gap tab-content">

            <!-- Tab Content 1 -->
            <div class="tab-pane fade active in">
              <div class="col-md-12 tab-content-text page-content pt-0">
                <div class="tab-list-content">
                  <div class="row">
                    <button class="btn-text font-weight-600" id='filter-btn'><span class="glyphicon glyphicon-filter"></span> Filter</button>
                  </div>

                  <div class="row" id="item-filters" style="display: none;" data-filter="all" data-sorter="cached_problems_count" data-search-filter="">
                    <div class="col-md-12">
                      <div class="col-md-6">
                        <p>Sort:</p>
                        <ul id="pfolio-filters" class="portfolio-filters sorter">
                          <li class="active"><a href="#" title="Sort by Number of Problems" data-sorter="cached_problems_count">Popular</a></li>
                          <li class=""><a href="#" title="Sort by Name" data-sorter="name">Name</a></li>
                          <li><a href="#" title="Sort by Date Created" data-sorter="created_at">New</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>


                  <div class="mt-20" id="topic-feed">
                    <% @topics.each_with_index do |topic, index| %>
                      <%= render(:partial => 'shared/items/topic_item', locals: { topic: topic }) %>
                      <% if index % 2 == 1 or index == @topics.count - 1 %>
                        <div class="clearfix"></div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div><!-- / #tab1 -->
          </div><!-- / .col-lg-10 -->
        </div><!-- / .row -->
      </div>

    </div>
  </div>
</div>

app/views/topics/index.js.erb
<% if @topics.count > 0 %>
  <% @topics.each_with_index do |topic, index| %>
    $('#topic-feed').append("<%= escape_javascript render(:partial => '/shared/items/topic_item', locals: { topic: topic }) %>");

    <% if index % 2 == 1 or index == @topics.count - 1 %>
      $('#topic-feed').append("<div class='clearfix'></div>");
    <% end %>
  <% end %>
<% end %>

app/views/topics/log.js.erb
<% if @versions.count > 0 %>
  $('.tab-content .tab-list-content').html("<%= escape_javascript render(:partial => '/shared/items/version_item', collection: @versions, as: :model ) %>");
<% else %>
  $(".tab-content .tab-list-content").html("<%= no_results_content('edits') %>");
<% end %>

$('.tab-content .tab-list-content').prepend("<div class='boxedtitle add-problem-title mb-40'><h2>Edits (<%=@versions.count%>)</h2></div>");

$content = $('.tab-content');
  setTimeout(function() {
	  MathJax.Hub.Queue(["Typeset", MathJax.Hub, $content[0]]);
} ,500);

app/views/topics/new.html.erb
<%= render 'shared/preview' %>

<div class="contact-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-offset-1 col-lg-10">
        <div class="form-wrapper">
  
          <div class="from-header">
					  <h2>New Topic</h2>
				  	<p>Duis dapibus aliquam mi, eget euismod sem scelerisque ut. Vivamus at elit quis urna adipiscing iaculis. Curabitur vitae velit in neque dictum blandit. Proin in iaculis neque.</p>
					</div>

					<%= form_with(model: @topic, local: true, id: "topic-form") do |form| %>
            <%= render 'shared/error_messages' %>
            <%= form.hidden_field :images, value: "#{@new_images}", id: "new-images" %>


            <div class="form-group">
              <%= form.label :name, "Topic Name *" %>
              <%= form.text_field :name, class: "form-control" %>
            </div> 

            <div class="form-group">
              <%= form.label :description, "Description *" %>
              <%= form.hidden_field :description, class: "mb-20 form-control", id: "topic_description" %>
              <trix-editor input="topic_description"></trix-editor>
              <span class="pull-right"><a target="_blank" href="/mathjax_cheatsheet" class="grey-link"><span class="glyphicon glyphicon-info-sign"></span> Math Formatting</a></span>

            </div>

            <!-- Action Buttons -->
            <div class="form-group">
              <span class="btn mb-5 btn-mult btn-ghost mr-5 preview-btn" data-toggle="modal" data-target="#preview-modal">Preview</span>
              <%= form.submit "Submit", class: "btn btn-mult mb-5", style: "display: inline-block; margin-top: 0;" %>
            </div>
          <% end %>   
     
        </div><!-- / .form-wrapper -->
      </div><!-- / .col-md-12 --> 
    </div><!-- / .row -->
  </div><!-- / container -->
</div><!-- / contact-3 -->

app/views/topics/problems.js.erb
<% if @problems.count > 0 %>
  $('.tab-content .tab-list-content').html("<%= escape_javascript render(:partial => '/shared/items/problem_item', locals: { problems_count: @problems.count }, collection: @problems, as: :problem ) %>");
<% else %>
  $(".tab-content .tab-list-content").html("<%= no_results_content('problems') %>");
<% end %>

$('.tab-content .tab-list-content').prepend("<div class='boxedtitle add-problem-title mb-40'><h2>Problems (<%=@problems.count%>)</h2></div>");

app/views/topics/proofs.js.erb
<% if @proofs.count > 0 %>
  $('.tab-content .tab-list-content').html("<%= escape_javascript render(:partial => '/shared/items/proof_item', collection: @proofs, as: :model ) %>");
  $content = $('.tab-content');
  setTimeout(function() {
	  MathJax.Hub.Queue(["Typeset", MathJax.Hub, $content[0]]);
} ,500);

<% else %>
  $(".tab-content .tab-list-content").html("<%= no_results_content('proofs') %>");
<% end %>

$('.tab-content .tab-list-content').prepend("<div class='boxedtitle add-problem-title mb-40'><h2>Proofs (<%=@proofs.count%>)</h2></div>");

app/views/topics/show.html.erb
<div class='wideContainer mt-60'>
  <div class='row'>
    <div class='col-md-8'>
      <div class='topic-feature'>
        <% if !@topic.featured_problem.image.blank? %>
          <%= link_to problem_path(@topic.featured_problem.id), class: 'topic-feature-image mb-15', 
					                                   style: "background-image: url(#{@topic.featured_problem.image})" do %>
            
					<% end %>
				<% end %>

        <div class='fancyCaption headerFont'>
          <p class='mb-0'>Featured Problem</p>
				</div>

        <%= link_to problem_path(@topic.featured_problem.id), 
				                         class: 'header-link-1' do %>
          <h1 class='header-h1'>
				    <%= @topic.featured_problem.title %>
			    </h1>
				<% end %>

				<div class="author-container" style='margin-top: 20px; margn-bottom: 20px;'>
				  <div class="author-img">
				    <a href="<%=user_path(@topic.featured_problem.user.id)%>"><img width="60" height="60" src="<%=user_avatar_src(@topic.featured_problem.user)%>" alt="Go to the profile of <%=@topic.featured_problem.user.name_or_username%>"></a>
				  </div>


          <div class='noWrapWithEllipsis headerFont' style='padding-top: 7.5px; padding-bottom: 7.5px;'>
            <a class="captionSmall captionStrong underlineLink fontSize-15" href="<%=user_path(@topic.featured_problem.user.id)%>"><%=@topic.featured_problem.user.name_or_username%></a>
            <div class="noWrapWithEllipsis captionSmall fontSize-15">
              <span class="time no-wrap"><%= time_ago_in_words(@topic.featured_problem.created_at) %> ago</span>
              <span class="dot-sep">·</span>
              <span class="views no-wrap"><%=pluralize(@topic.featured_problem.cached_proofs_count, 'proof')%></span>
            </div>
          </div>
				</div>
			</div>
      <div>
        <h3 class='headerFont pb-8 fontWeight-600 darktype fontSize-16 bb-light'>
          Latest
        </h3>

        <div class='pt-30'>
          <div class='topic-problem-feed'>
            <% @topic.problems.order(created_at: :desc).each_with_index do |problem, index| %>
              <%= render(:partial => 'problems/stream_item', locals: { problem: problem }) %>
            <% end %>
          </div>
        </div>
      </div>
	  </div>
    <div class='col-md-4'>
      <div class='topic-sidebar'>
        <%= render '/shared/sidebars/widgets/topic_meta', locals: { @topic => @topic } %>
        <%@related_topics = @topic.related_topics%>
        <% if @related_topics.length > 2 %>
          <%= render '/shared/sidebars/widgets/related_topics', locals: { @related_topics => @related_topics } %>
        <% end %>

        <% if @topic.problems.count > 2 %>
          <%= render '/shared/sidebars/widgets/popular_problems_widget', locals: { @topic => @topic } %>
        <% end %>
			</div>
		</div>
	</div>
</div>

app/views/topics/unfollow.js.erb
$('#topic-follow-<%=@topic.id%>').html("<a href='<%=topic_follow_path(@topic.id)%>' data-remote='true' data-method='post'><button class='" + $('#topic-follow-<%=@topic.id%>').data("class") + "'>Follow</button></a>");

$('#topic-<%=@topic.id%>-followers').text('<%= pluralize(@topic.followers.count, "Follower") %>');

if ($("#followers-stat-val").length > 0) {
  $("#followers-stat-val").text('<%= @topic.followers.count %>');
}

app/views/topics/users.js.erb
$('.topic-content').empty();