config/routes.rb
Rails.application.routes.draw do

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]

  get '/comments/:id/cancel_edit_comment', to: 'comments#cancel_edit', as: :cancel_edit_comment
  get '/comments/cancel_new_comment', to: 'comments#cancel_new', as: :cancel_new_comment
  #get '/proofs/:id/cancel_new_comment', to: 'proofs#cancel_new', as: :cancel_new_comment


  resources :topics do
    member do
      get :problems
      get :proofs
      get :followers
      get :log
      get :description
    end

    collection do
      get :search
    end
  end

  resources :proofs do
    member do
      get :log
      get :comments
    end
  end

  get '/proofs/:id/cancel_edit', to: 'proofs#cancel_edit', as: :cancel_edit
  get 'users/show'

  get 'static_pages/landing'
  get '/about', to: 'static_pages#about', as: :about
  get '/contact_us', to: 'static_pages#contact', as: :contact
  get '/tour', to: 'static_pages#tour', as: :tour

  get '/help', to: 'help_center#help', as: :help

  ################## help center categories #####################

  get '/help/:category', to: 'help_center#category', as: :help_center_category
=begin
  get '/help/problems', to: 'help_center#problems', as: :help_category_problems
  get '/help/reputation', to: 'help_center#reputation', as: :help_category_reputation
  get '/help/proofs', to: 'help_center#proofs', as: :help_category_proofs
  get '/help/account', to: 'help_center#account', as: :help_category_account
  get '/help/privileges', to: 'help_center#privileges', as: :help_category_privileges
=end
  ################ help center articles ####################

  get '/help/:category/:article', to: 'help_center#article', as: :help_center_article
=begin
  #get '/help/priviliges/:id', to: 'help_center#priviliges', as: :priviliges
  get '/help/mathjax_cheatsheet', to: 'help_center#mathjax_cheatsheet', as: :mathjax_cheatsheet
  get '/help/topics', to: 'help_center#on_topics', as: :on_topics
  get '/help/good-problems', to: 'help_center#good_problems', as: :good_problems
  get '/help/problem-feed', to: 'help_center#on_problem_feed', as: :on_problem_feed
  get '/help/expected-behavior', to: 'help_center#expected_behavior', as: :expected_behavior
  get '/help/editing-posts', to: 'help_center#editing_posts', as: :editing_posts
  get '/help/creating-topics', to: 'help_center#creating_topics', as: :creating_topics
  get '/help/deleting-posts', to: 'help_center#deleting_posts', as: :deleting_posts
  #get '/help/reputation', to: 'help_center#reputation', as: :reputation
  get '/help/badges', to: 'help_center#badges', as: :badges
=end

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
			root 'problems#feed'
		end
		
		unauthenticated do
			root 'static_pages#landing'
		end
  end
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :problems
      get :comments
      get :problem_edits
      get :problems_following
      get :proofs
      get :activity
      get :followers
      get :following
      get :topic_edits
      get :topics_following
      post :follow
      delete :unfollow
      patch :update_image
    end
  end

  resources :reports, only: [:new, :create, :update, :index, :show] do
    collection do
      get 'reserved'
      get 'history'
      get 'users'
      get 'help'
    end

    member do
      get 'close'
      put 'close'
      put 'decline'
      put 'reserve'
      delete 'unreserve'
    end
  end

  resources :versions, only: [:show]
  resources :problems do
    member do
      get :followers
      get :comments
    end
  end
  get "/feed", to: "problems#feed", as: :feed

  get '/problems/:id/log', to: 'problems#log', as: :problem_log
  resources :images, only: [:create, :destroy]
  put '/vote', to: 'users#vote', as: :vote

  post '/problems/:id/bookmark', to: 'problems#bookmark', as: :problem_bookmark
	delete '/problems/:id/unbookmark', to: 'problems#unbookmark', as: :problem_unbookmark

  post '/topics/:id/follow', to: 'topics#follow', as: :topic_follow
	delete '/topics/:id/unfollow', to: 'topics#unfollow', as: :topic_unfollow

  resources :conversations do
    resources :messages
  end

  post '/conversations/:id/mark_as_read', to: 'conversations#mark_as_read', as: :mark_as_read_message
  post '/conversations/mark_all_as_read', to: 'conversations#mark_all_as_read', as: :mark_all_as_read_messages
 
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end

  get '/search', to: "search#search", as: :search

  get '/main_search', to: 'users#main_search', as: :main_search
  mathjax 'mathjax'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/help_center_controller.rb
class HelpCenterController < ApplicationController
  include HelpCenterHelper

  before_action :category_exists,  only: [:category]
  before_action :article_exists, only: [:article] 
 
  def help
  end

  def category
  end

  def article
  end

  ########### Help Center Categories #############
=begin
  def general
  end

  def problems
  end

  def reputation
  end

  def priviliges
    #@privilige = params[:id].to_i
  end

  def proofs
  end

  def account
  end

  def mathjax_cheatsheet
  end

  def on_topics
  end

  def good_problems
  end

  def on_problem_feed
  end

  def expected_behavior
  end

  def editing_posts
  end
 
  def creating_topics
  end

  def deleting_posts
  end

  def badges
  end
=end

  private

  def category_exists
    @category = params[:category].titleize
    if !help_center_categories.include? @category
      raise ActionController::RoutingError.new('Not Found')
    end
    #lookup_context.exists?("help_center/#{@category}find")
  end

  def article_exists
    @category = params[:category].titleize
    @article = params[:article].titleize

    if !help_center_articles(@category).include? @article
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/helpers/help_center_helper.rb
module HelpCenterHelper
  def help_center_categories
    ["General", "Problems", "Reputation", "Privileges", "Proofs", "Account"]
  end

  def help_center_articles(category)
    case category
    when "General"
      ["What Is The Expected Behavior?", "How Do I Write Math On My Posts?",
       "Why Can People Edit My Posts?", "How Can A Post Be Deleted?"]
    when "Problems"
      ["What Are Topics And How Do I Use Them?", 
       "How Do I Write A Good Problem?", 
       "How Do I Find Problems That I Am Interested In?"]
    when "Reputation"
      ["What Is Reputation And How Do I Earn It?", "What Are Badges?"]
    when "Privileges"
      ["Create Posts", "Upvote", "Comment", "Downvote", "Report", 
       "Edit Posts", "Moderator Tools"]
    when "Proofs"
      ["How Do I Write A Good Proof?", "Can I Prove My Own Problem?", 
       "Why And How Has My Proof Been Deleted?"]
    when "Account"
      ["I Forgot My Password: How Do I Reset It?", 
       "How Do I Delete My Account?", "How Do I Create An Account?", 
       "Why Should I Create An Account?"]
    end
  end

  def is_privilege_category?(category)
    category == "Privileges"
  end

  def privilege_reputation(article)
    case article
    when "Create Posts"
      '(0)'
    when "Upvote"
      '(10)'
    when "Comment"
      '(50)'
    when "Downvote"
      '(100)'
    when "Report"
      '(300)'
    when "Edit Posts"
      '(1500)'
    when "Moderator Tools"
      '(7500)'
    end
  end
end

app/views/help_center/partials/_badges.html.erb
<p class='reg-p'>Each user has a colored badge that serves as a sort of rank, and determines the level of trust he or she has earned based on his or her reputation score. This color badge appears on the user's standard card and provides a quick visual representation of the user's trustworthiness and site prestige.</p>
<p class='reg-p'>The following are the badges along with the corresponding reputation level needed to earn you that badge:</p>
<div class="row">
  <div class="col-xs-6 col-sm-4">
    <p class="badge-label" style="background-color: #373940;"><span class="fa fa-trophy mr-5"></span> 0</p>
  </div>
  <div class="col-xs-6 col-sm-4">
    <p class="badge-label" style="background-color: #ff7361;"><span class="fa fa-trophy mr-5"></span> 10</p>
  </div>
  <div class="col-xs-6 col-sm-4">
    <p class="badge-label" style="background-color: #2E8B57;"><span class="fa fa-trophy mr-5"></span> 200</p>
  </div>
  <div class="col-xs-6 col-sm-4">
    <p class="badge-label" style="background-color: #1e73be;"><span class="fa fa-trophy mr-5"></span> 1000</p>
  </div>
  <div class="col-xs-6 col-sm-4">
    <p class="badge-label" style="background-color: #544f87;"><span class="fa fa-trophy mr-5"></span> 5000</p>
  </div>
  <div class="col-xs-6 col-sm-4">
    <p class="badge-label" style="background-color: #dd9934;"><span class="fa fa-trophy mr-5"></span> 25000</p>
  </div>
</div>

app/views/help_center/partials/_creating_topics.html.erb
<p class='reg-p'>Trusted users with at least 3000 reputation can create new topics. You should only create a new topic when you are sure that your problem covers a new topic and no one else has asked about before. As a general rule, you should avoid creating new topics if possible.</p>
<h3>How do I create a new topic?</h3>
<p class='reg-p'>If you are a trusted member then a link to create a new topic will appear on your homepage sidebar. When creating the topic, bear in mind that topic names must not be longer than 35 characters, and can only use the following chacter set: <code>a-z</code>, <code>0-9</code>, <code>+</code>, <code>#</code>, <code>-</code>, <code>.</code>. You must provide a description of the topic as well.</p>
<h3>What happens after a new topic is created?</h3>
<p class='reg-p'>The new topic will now be available for all other users to use and follow. If they are not used by any questions in a 4 month period, the topic will be removed.</p>
<p class='reg-p'>Please create topics responsibly!</p>

app/views/help_center/partials/_deleting_posts.html.erb
<h3>By a User:</h3>

<ul>
  <li class='reg-item'><b>The author</b> can typically delete their own posts, except when: 
    <ul>
      <li>the problem in question has at least one proof with at least one upvote.</li>
      <li>the proof in question has at least one upvote (it doesn't matter if the overall score is negative).</li>
    </ul>
  </li>
  <li class='reg-item'><b>Moderators</b> can delete any posts instantly.</li>
  <li class='reg-item'><b>Users with 15000 reputation or more</b> can vote to delete a post that is in the "review queue". 3 votes are needed for the post to be deleted.</li>
</ul>

<h3>By the System:</h3>

<ul>
  <li class='reg-item'><b>Dead problem:</b> Problems that are over 60 days old, with a negative score and no proofs will automatically be deleted.</li>
  <li class='reg-item'><b>Reported problems:</b> Problems that are over 30 days old, with 3 or more reports and no proofs will automatically be deleted.</li>
  <li class='reg-item'><b>Spam or abusive posts</b> If a problem or proof receives 6 spam or offensive reports, they will be automatically deleted. The owner of the post will also receive -100 reputation points.
  <li class='reg-item'><b>Bad comments:</b> Comments that have a voting score of -5 or less, or 3 or more reports will automatically be deleted.</li>
</ul>

<h3>What is the Review Queue?</h3>
<p class='reg-p'>Posts in the review queue are posts that are deeply flawed and in need of an improvement or in the case that it can't be improved, a deletion. Here, posts are reviewed thoroughly by moderators and users with <%= link_to "deletion priviliges", "#deletion-priv-faq", easing: "linear" %>. An effort is made to edit the post and to mark it as OK if it can be improved, otherwise they are deleted.</p>
<h3>How does a post get put in the Review Queue?</h3>
<ul>
  <li class='reg-item'>A problem with a voting score of -6 is put in the queue.</li>
  <li class='reg-item'>A proof with a voting score of -4 is put in the queue.</li>
  <li class='reg-item'>If a post is reported, the reviewer can send the post to the queue.</li>
<!--
  <li class='reg-item'>Any post with 3 or more reports (that are not spam or offensive flag reports) is put in the queue.</li>
-->
</ul>
<h3>What Happens After my Post has Been Taken out of the Review Queue?</h3>
<p class='reg-p'>If the post manages to get out of the review queue, the reports expire and its voting score stays the same. A secondary score will be kept from the moment it is taken out of the review queue, and if this score falls below a -3, it will automatically be deleted. If the post receives 1 or more reports after being released from the review queue, it will also be deleted.</p>
 

app/views/help_center/partials/_editing_posts.html.erb
<p class='reg-p'>This site is a collaborative effort. If you see a problem or topic that needs improvement, click edit!<p>
<p class='reg-p'>We believe that the collective wisdom of users ensures the quality of posts. Editing is important for keeping problems and topics clear, grammatically correct and relevant.<p>
<h3>When to edit posts</h3>
<p class='reg-p'> Whenever you see a post that can be improved, it is ecouraged to edit it. Edits are expected to leave the post better than how you found it. Here are some reasons for edits: </p>
<ul>
  <li class='reg-item'>To improve spelling, grammar or punctuation</li>
  <li class='reg-item'>To clarify the meaning of the post. It is important not to change the intended meaning of the poster.</li>
  <li class='reg-item'>To include important information that is found in the comments. Sometimes additional information or a clarification arises in the comments. It is better to keep all of the relevant information in one place.</li>
  <li class='reg-item'>To correct a mistake or error made</li>
  <li class='reg-item'>To add citations, links or resources</li>
</ul>
<h3>Who can edit posts?</h3>
<p class='reg-p'>Only trusted members of the community can edit posts. You need at least 2500 reputation points to edit problems and proofs, and at least 3000 reputation to edit topics. The creator of the post can always edit their own post, regardless of their reputation.</p>
<h3>What happens after I edit a post?</h3>
<p class='reg-p'>The post will update to show the latest editor as well as the original creator. All edits are saved and tracked in the posts version history. Each version will be viewable along with the editor in the post's log. Editing a post will bump it to the top of the feed.</p>
<h3>What if the edit was bad?</h3>
<p class='reg-p'>Common users can report edits. If the latest edit gets 5 or more reports then the latest version will be reverted to its previous version and the edit will disappear from the log. Trusted users with at least 5000 reputation, and original authors can rollback edits automatically.</p>

app/views/help_center/partials/_good_problems.html.erb
<p class='reg-p'>Improve your chances of getting a proof by writing good problems.</p>
<p class='reg-p'>Make sure your problem is not a duplicate and is different from the rest. <%= link_to "Search", problems_path %>, research and keep track of what you find. You can link problems that have not helped you so that others can better understand your question and make sure it is not repeated.</p>
<h3>Write a title that summarizes the problem</h3>
<p class='reg-p'>The title is the first thing that users will see, and if it is not good, people will lose interest and won't read the rest. Here are some tips for making a good title:</p>
<ul>
  <li class='reg-item'>Sum up your entire problem in one sentence. Include details that will help people identify and solve your problem. Iclude any constraints or variants to your problem that make it different from similar problems already on the site.</li>
  <li class='reg-item'>Spelling, grammar and punctuation are important! Make sure you proof-read it or have someone proof-read it for you if your english is not good.</li>
  <li class='reg-item'>Write the title last if you are having trouble summarizing the problem. Sometimes writing the problem first can make it easier for you to describe the problem.</li>
</ul>
<h3>Include relevant tags</h3>
<p class='reg-p'>Make sure that the tags you submit are relevant to the problem by reading their descriptions. The system will suggest topics that match what you have typed. See also: <%= link_to "What are tags/topics and how do I use them?", on_topics_path %></p>
<h3>Proof-read before posting</h3>
<p class='reg-p'>Read the problem from start to finish and make sure everything is clear and makes since. Add any details you missed and read through it again. Before posting, if you wrote the title first, read it again and make sure it still describes the problem.</p>
<h3>Make sure the problem is to prove a mathematical statement</h3>
<p class='reg-p'>The purpose of this site is not to solve computational problems and make calculations: it is about the conscious understanding of abstract mathematical truth, and why it is true. Forget about calculating, and ask questions like why a particular statement is true or false, and why a certain pattern exists.</p>
<h3>Respond to feedback after posting problem</h3>
<p class='reg-p'>After posting your problem, frequently check on it to see if anyone comments on it. If you missed a piece of information or made an error in your problem, be ready to edit your problem and fix it. If someone posts a proof, be ready to provide feedback.</p>

app/views/help_center/partials/_more_help.html.erb
<p class='reg-p'>If you have a question, need more information, are experiencing an error, or want to report a security vulnerabilty, please <%= link_to "contact us directly", contact_path %>.</p>

app/views/help_center/partials/_on_problem_feed.html.erb
<p class='reg-p'>The primary way that you will find problems you are interested in is through your problem feed. Problems that you follow and problems within topics that you follow will show up in your feed. It is important that you follow topics that you are interested in, so that your feed can be tailored to you.</p>
<h3> Search for specific problems </h3>
<p class='reg-p'> If you want to browse and search from all problems that contain some phrase or word, you can do so <%= link_to "here", problems_path %>. You can refine your search by filtering problems with proofs or ones that don't have any yet. You can also sort based on date created or modified, problems with most upvotes or problems with most proofs.</p>

app/views/help_center/partials/_on_topics.html.erb
<p class='reg-p'> Topics are a way of connecting users with problems they will be able to answer by sorting problems into specific, well-defined categories.</p>
<p class='reg-p'> Topics are also used to help you identify problems that are relavent or interesting to you. Users can follow topics in order to recieve problems within specific topics in their <%= signed_in? ? link_to("feed", feed_path) : "feed" %>. You can <%= link_to "browse and search new topics", topics_path %> in the topics index page to improve your feed.</p>
<p class='reg-p'> Each problem has to have at least one topic. Clicking on the topic tag corresponding to a problem brings you to a page that shows you a description of what the topic is. You can also see all problems and proofs within that topic, the past edits made to that topic (<%= link_to "See how editing works", editing_posts_path %>), and the users who are following it.</p>
<p class='reg-p'>Not everyone can <%= link_to "create a new topic", creating_topics_path %>. A certain amount of reputation is needed before you can start creating new topics. Even if you have sufficient reputation, you should only create a new topic when you are sure that your problem covers a new topic and no one else has asked about before. As a general rule, you should avoid creating new topics if possible.</p>
<p class='reg-p'>Users with sufficient reputation can edit the topic tags of a problem if they feel a certain tag was used innapropriately or if the problem is missing a topic.</p>

app/views/help_center/partials/_reputation.html.erb
<p class='reg-p'>Reputation is a rough measure of how much the community trusts you, and it is earned by convincing users that you know what you are talking about. The more reputation you earn the more <%= link_to "priviliges", priviliges_path(1) %> you gain and the more you can do on the site. It is set up this way because we believe in the wisdom of our users so we want them to run the site as a collective community.</p>
<h3>How to earn reputation</h3>
<p class='reg-p'>As mentioned before, the primary way to earn reputation is by convincing people that you know what you are talking about. This is primarily done by writing good problems and proofs. Votes on these posts can make you either gain or lose reputation.</p>
<h4>Ways to gain reputation:</h4>
<ul>
  <li class='reg-item'>Problem is voted up: +5</li>
  <li class='reg-item'>Proof is voted up: +10</li>
  <li class='reg-item'>Comment is voted up: +2</li>
</ul>
<h4>Ways to lose reputation:</h4>
<ul>
  <li class='reg-item'>Problem is voted down: -2</li>
  <li class='reg-item'>Proof is voted down: -2</li>
  <li class='reg-item'>Comment is voted down: -1</li>
  <li class='reg-item'>You vote down a post: -1</li>
</ul>
<p class='reg-p'> All users start with 0 reputation and it can never drop below 0. Deleting a post will not affect the scores of the authors and people involved. When a user reverses a vote, the corresponding reputation loss or gain will be reverted as well. Note that a user cannot vote on his or her own post.</p>
 