config/routes.rb
Rails.application.routes.draw do

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]

  get '/comments/:id/cancel_edit_comment', to: 'comments#cancel_edit', as: :cancel_edit_comment
  get '/comments/cancel_new_comment', to: 'comments#cancel_new', as: :cancel_new_comment
  #get '/proofs/:id/cancel_new_comment', to: 'proofs#cancel_new', as: :cancel_new_comment


  resources :topics do
    member do
      get :problems
      get :proofs
      get :followers
      get :log
      get :description
    end

    collection do
      get :search
    end
  end

  resources :proofs do
    member do
      get :log
      get :comments
    end
  end

  get '/proofs/:id/cancel_edit', to: 'proofs#cancel_edit', as: :cancel_edit
  get 'users/show'

  get 'static_pages/landing'
  get '/about', to: 'static_pages#about', as: :about
  get '/contact_us', to: 'static_pages#contact', as: :contact
  get '/tour', to: 'static_pages#tour', as: :tour

  get '/help', to: 'help_center#help', as: :help

  ################## help center categories #####################

  get '/help/:category', to: 'help_center#category', as: :help_center_category
=begin
  get '/help/problems', to: 'help_center#problems', as: :help_category_problems
  get '/help/reputation', to: 'help_center#reputation', as: :help_category_reputation
  get '/help/proofs', to: 'help_center#proofs', as: :help_category_proofs
  get '/help/account', to: 'help_center#account', as: :help_category_account
  get '/help/privileges', to: 'help_center#privileges', as: :help_category_privileges
=end
  ################ help center articles ####################

  get '/help/:category/:article', to: 'help_center#article', as: :help_center_article
=begin
  #get '/help/priviliges/:id', to: 'help_center#priviliges', as: :priviliges
  get '/help/mathjax_cheatsheet', to: 'help_center#mathjax_cheatsheet', as: :mathjax_cheatsheet
  get '/help/topics', to: 'help_center#on_topics', as: :on_topics
  get '/help/good-problems', to: 'help_center#good_problems', as: :good_problems
  get '/help/problem-feed', to: 'help_center#on_problem_feed', as: :on_problem_feed
  get '/help/expected-behavior', to: 'help_center#expected_behavior', as: :expected_behavior
  get '/help/editing-posts', to: 'help_center#editing_posts', as: :editing_posts
  get '/help/creating-topics', to: 'help_center#creating_topics', as: :creating_topics
  get '/help/deleting-posts', to: 'help_center#deleting_posts', as: :deleting_posts
  #get '/help/reputation', to: 'help_center#reputation', as: :reputation
  get '/help/badges', to: 'help_center#badges', as: :badges
=end

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
			root 'problems#feed'
		end
		
		unauthenticated do
			root 'static_pages#landing'
		end
  end
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :problems
      get :comments
      get :problem_edits
      get :problems_following
      get :proofs
      get :activity
      get :followers
      get :following
      get :topic_edits
      get :topics_following
      post :follow
      delete :unfollow
      patch :update_image
    end
  end

  resources :reports, only: [:new, :create, :update, :index, :show] do
    collection do
      get 'reserved'
      get 'history'
      get 'users'
      get 'help'
    end

    member do
      get 'close'
      put 'close'
      put 'decline'
      put 'reserve'
      delete 'unreserve'
    end
  end

  resources :versions, only: [:show]
  resources :problems do
    member do
      get :followers
      get :comments
    end
  end
  get "/feed", to: "problems#feed", as: :feed

  get '/problems/:id/log', to: 'problems#log', as: :problem_log
  resources :images, only: [:create, :destroy]
  put '/vote', to: 'users#vote', as: :vote

  post '/problems/:id/bookmark', to: 'problems#bookmark', as: :problem_bookmark
	delete '/problems/:id/unbookmark', to: 'problems#unbookmark', as: :problem_unbookmark

  post '/topics/:id/follow', to: 'topics#follow', as: :topic_follow
	delete '/topics/:id/unfollow', to: 'topics#unfollow', as: :topic_unfollow

  resources :conversations do
    resources :messages
  end

  post '/conversations/:id/mark_as_read', to: 'conversations#mark_as_read', as: :mark_as_read_message
  post '/conversations/mark_all_as_read', to: 'conversations#mark_all_as_read', as: :mark_all_as_read_messages
 
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end

  get '/search', to: "search#search", as: :search

  get '/main_search', to: 'users#main_search', as: :main_search
  mathjax 'mathjax'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if @exception %>
  <div id="error_explanation">
   <ul class='mb-15'>
    <li><%= @exception.message %></li>
    </ul>
  </div>
<% elsif @error %>
  <div id="error_explanation">
   <ul>
    <li><%= @error %></li>
    </ul>
  </div>
<% elsif @user %>
	<% model = @user %>
<% elsif @topic %>
  <% model = @topic %>
<% elsif @comment %>
  <% model = @comment %>
<% elsif @proof %>
  <% model = @proof %>
<% elsif @problem %>
  <% model = @problem %>
<% end %>

<% if  !@exception and !@error and model.errors.any? %>
  <div id="error_explanation">
   <ul class='mb-15'>
    <li><%= model.errors.full_messages.first %></li>
    </ul>
  </div>
<% elsif flash[:failed_login] %>
  <div id="error_explanation">
   <ul class='mb-15'>
    <li><%= flash[:failed_login] %></li>
    </ul>
  </div>
<% elsif flash[:failed_problem_create] %>
  <div id="error_explanation">
   <ul class='mb-15'>
    <li><%= flash[:failed_problem_create] %></li>
    </ul>
  </div>
<% elsif flash[:failed_proof_create]%>
  <ul class='mb-15'>
    <li><%= flash[:failed_proof_create] %></li>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.present? %>
  <div id="flash-message-wrapper" class="<%= flash_class %>">
    <p><%= flash_message %></p>
  </div>
<% end %>

<script>
  setTimeout(function() {
    $('#flash-message-wrapper').fadeOut("slow", function() {
      $(this).remove();
    });
  }, 7500);
</script>
<!--
<%# if flash.present? %>
  <script>
    // toastr flash messages
  toastr.options = {
    "closeButton": false,
    "debug": false,
    "newestOnTop": false,
    "progressBar": true,
    "positionClass": "toast-top-left",
    "preventDuplicates": false,
    "onclick": null,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "8000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "slideDown",
    "hideMethod": "slideUp"
  }

  </script>
 
  <div id='flash'>
   <script> 
     <%# if flash[:success] %>
       var $toastContent = $('<span><%#= flash[:success] %></span>');
       toastr.success($toastContent)
     <%# end %>
     <%# if flash[:notice] %>
       var $toastContent = $('<span><%#= flash[:notice] %></span>');
       toastr.info($toastContent)
     <%# end %>
     <%# if flash[:error] %>
       var $toastContent = $('<span><%#= flash[:error] %></span>');
       toastr.error($toastContent)
     <%# end %>
     <%# if flash[:alert] %>
       var $toastContent = $('<span><%#= flash[:alert] %></span>');
       toastr.warning($toastContent)
     <%# end %> 

   </script>
  </div>
<%# end %>
-->

app/views/shared/_general_preview_template.html.erb
<!-- General Preview -->
<div class="bp-comment mb-100 pa-20 generalPreview postPreview" style='border:1px solid rgba(0,0,0,0.14);'> 

  <div class='fancyCaption'>
    <p class='mb-10 fontSize-13 headerFont fontWeight-700 float-left'><i class='fa fa-eye mr-5'></i>Content preview</p>

    <div class="float-right mt-0 fontSize-18" title='Close preview'>
      <i class='fa fa-times close' style='color: rgba(0,0,0,0.84); cursor: pointer;'></i>
	  </div>
		<div class='clearfix'></div>
  </div>
 
                  
  <div class="comment-content mt-20 darkType bodyFont bodyStyles general-preview-content">
    {{html content}}
  </div>	
</div> <!-- bp-comment -->

app/views/shared/_loader.html.erb
<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>

app/views/shared/_main_site_tabs.html.erb
<!-- Tabs -->
<div class="col-lg-2 no-gap">
	<ul class="tabs-list" role="tablist">

    <% if signed_in? %>
		  <!-- Tab 1 -->
		  <li role="presentation" class="<%='active' if current_page?(feed_path) or (signed_in? and current_page?(root_path)) %>">
			  <a href="<%= feed_path %>">
				  <div class="tab-bottom">
					  <p><span class="glyphicon glyphicon-home mr-5"></span> Home</p>
				  </div>
			  </a>
		  </li>
    <% end %>

    <!-- Tab 2 -->
		<li role="presentation" class="<%= 'active' if current_page?(problems_path)%>">
			<a href="<%= problems_path %>">
				<div class="tab-bottom">
					<p><span class="fa fa-question-circle mr-5"></span> Browse Problems</p>
				</div>
			</a>
		</li>


		<!-- Tab 3 -->
		<li role="presentation" class="<%= 'active' if current_page?(topics_path)%>">
			<a href="<%= topics_path %>">
				<div class="tab-bottom">
					<p><span class="glyphicon glyphicon-tag mr-5"></span> Browse Topics</p>
				</div>
			</a>
		</li>

		<!-- Tab 4 -->
		<li role="presentation" class="<%= 'active' if current_page?(users_path)%>">
			<a href="<%= users_path %>">
				<div class="tab-bottom">
					<p><span class="fa fa-users mr-5"></span> Browse Users</p>
				</div>
			</a>
		</li>
	</ul>
</div><!-- / .col-lg-2 -->

app/views/shared/_messages_dropdown.html.erb
<div class="dropdown-container">
  <div class="dropdown-toolbar">
    <div class="dropdown-toolbar-actions">
      <% if current_user.unread_messages.count > 0 %>
        <%= link_to "Mark all as read", mark_all_as_read_messages_path, method: :post, remote: true, class: "mark-all-as-read-link" %>
      <% end %>
    </div>
    <span class="dropdown-toolbar-title">Messages (<%=current_user.unread_messages.count%>)</span>
    <div class="clearfix"></div>
  </div><!-- /dropdown-toolbar -->

  <ul class="dropdown-menu-notifications">
  </ul>
  <% if current_user.mailbox.conversations.count == 0 %>
    <div class="no-messages-container">
      <img src="/assets/no_messages_icon.png" alt="conversations icon">
		  <p class="font-weight-600 font-size-15">You have no messages.</p>
	  </div>
  <% end %>
  
  <% if current_user.mailbox.conversations.count > 0 %>
    <div class="dropdown-footer text-center">
      <%= link_to "View All", conversation_path(current_user.mailbox.conversations.last) %>
    </div><!-- /dropdown-footer -->
  <% end %>
</div><!-- /dropdown-container -->

app/views/shared/_no_privilige_modal.html.erb
<div id="noPriviligeModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" style="position: absolute; font-size: 30px;">&times;</button>
      <div class="modal-header" style="border-bottom: none; background: url(/assets/bad_math.jpg); background-size: contain; background-repeat: no-repeat; width: 100%; height: 0; padding-top: 33.56%;">
      </div>
      <div class="modal-body text-center" style="padding: 0px 50px 40px 50px;">
        <h3> Thanks for your feedback!</h3>
        <div class='custom-content'>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_no_results_found.html.erb
<div class='no-results-found pt-20'>
  <img src='/assets/no_data.svg'>
	<p class='lightType headerFont fontSize-18 pt-20'> No results found... </p>
</div>

app/views/shared/_not_signed_in_action_modal.html.erb
<div id="signinActionModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="border-bottom: none; padding: 8px 15px 0 15px;">
        <button type="button" class="close" data-dismiss="modal" style="font-size: 30px;">&times;</button>
      </div>
      <div class="modal-body text-center" style="padding: 0px 50px 40px 50px;">
        <img class="text-center" style="max-width: 33%; height: auto; display: block; margin: auto;" src="/assets/math_world.jpg">
        <h3> Thanks for your feedback!</h3>
        <p>Setting up an account is free and easy. Set up an account today and start earning privileges like voting, posting and commenting.</p>
        <%= link_to "Sign up", new_user_registration_path, class: "btn text-center mb-10" %>
        <p> Have an account? <%= link_to "Log in", new_user_session_path %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_notifications_dropdown.html.erb
<div class="dropdown-container">
  <div class="dropdown-toolbar">
    <span class="dropdown-toolbar-title">Notifications (<%=current_user.unread_notifications.count%>)</span>
  </div><!-- /dropdown-toolbar -->

  <ul class="dropdown-menu-notifications">
      
  </ul>
  <% if current_user.unread_notifications.count == 0 %>
    <div class="no-messages-container">
      <img src="/assets/no_notifications_icon.png" alt="conversations icon">
		  <p class="font-weight-600 font-size-15">You have no notifications.</p>
	  </div>
  <% end %>
  
  <div class="dropdown-footer text-center">
    <%= link_to "View All", notifications_path %>
  </div><!-- /dropdown-footer -->
</div><!-- /dropdown-container -->

app/views/shared/_preloader.html.erb
<!-- ========== Preloader ========== -->

<div class="preloader">
  <img src="/assets/loader.svg" alt="Loading...">
</div>

app/views/shared/_preview.html.erb
<div class="modal fade in" id="preview-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"> Markdown Preview </h4>
			</div>
			<div class="modal-body">
				<div class="preview_content" style="border: none;">
					<p>  </p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/shared/_user_list_modal.html.erb
<div class="modal fade in" id="userListModal" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
		  <div class="modal-header" style="padding: 10px;">
        <button type="button" class="close" data-dismiss="modal" style="font-size: 30px;">&times;</button>
			  <span class="modal-title" style="font-weight: 600; font-size: 1.4em; line-height: 1.4em;"> Followers </span>
		  </div>
		  <div class="modal-body" style="padding: 0;">
			</div>
    </div>
  </div>
</div>