config/routes.rb
Rails.application.routes.draw do

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]

  get '/comments/:id/cancel_edit_comment', to: 'comments#cancel_edit', as: :cancel_edit_comment
  get '/comments/cancel_new_comment', to: 'comments#cancel_new', as: :cancel_new_comment
  #get '/proofs/:id/cancel_new_comment', to: 'proofs#cancel_new', as: :cancel_new_comment


  resources :topics do
    member do
      get :problems
      get :proofs
      get :followers
      get :log
      get :description
    end

    collection do
      get :search
    end
  end

  resources :proofs do
    member do
      get :log
      get :comments
    end
  end

  get '/proofs/:id/cancel_edit', to: 'proofs#cancel_edit', as: :cancel_edit
  get 'users/show'

  get 'static_pages/landing'
  get '/about', to: 'static_pages#about', as: :about
  get '/contact_us', to: 'static_pages#contact', as: :contact
  get '/tour', to: 'static_pages#tour', as: :tour

  get '/help', to: 'help_center#help', as: :help

  ################## help center categories #####################

  get '/help/:category', to: 'help_center#category', as: :help_center_category
=begin
  get '/help/problems', to: 'help_center#problems', as: :help_category_problems
  get '/help/reputation', to: 'help_center#reputation', as: :help_category_reputation
  get '/help/proofs', to: 'help_center#proofs', as: :help_category_proofs
  get '/help/account', to: 'help_center#account', as: :help_category_account
  get '/help/privileges', to: 'help_center#privileges', as: :help_category_privileges
=end
  ################ help center articles ####################

  get '/help/:category/:article', to: 'help_center#article', as: :help_center_article
=begin
  #get '/help/priviliges/:id', to: 'help_center#priviliges', as: :priviliges
  get '/help/mathjax_cheatsheet', to: 'help_center#mathjax_cheatsheet', as: :mathjax_cheatsheet
  get '/help/topics', to: 'help_center#on_topics', as: :on_topics
  get '/help/good-problems', to: 'help_center#good_problems', as: :good_problems
  get '/help/problem-feed', to: 'help_center#on_problem_feed', as: :on_problem_feed
  get '/help/expected-behavior', to: 'help_center#expected_behavior', as: :expected_behavior
  get '/help/editing-posts', to: 'help_center#editing_posts', as: :editing_posts
  get '/help/creating-topics', to: 'help_center#creating_topics', as: :creating_topics
  get '/help/deleting-posts', to: 'help_center#deleting_posts', as: :deleting_posts
  #get '/help/reputation', to: 'help_center#reputation', as: :reputation
  get '/help/badges', to: 'help_center#badges', as: :badges
=end

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
			root 'problems#feed'
		end
		
		unauthenticated do
			root 'static_pages#landing'
		end
  end
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :problems
      get :comments
      get :problem_edits
      get :problems_following
      get :proofs
      get :activity
      get :followers
      get :following
      get :topic_edits
      get :topics_following
      post :follow
      delete :unfollow
      patch :update_image
    end
  end

  resources :reports, only: [:new, :create, :update, :index, :show] do
    collection do
      get 'reserved'
      get 'history'
      get 'users'
      get 'help'
    end

    member do
      get 'close'
      put 'close'
      put 'decline'
      put 'reserve'
      delete 'unreserve'
    end
  end

  resources :versions, only: [:show]
  resources :problems do
    member do
      get :followers
      get :comments
    end
  end
  get "/feed", to: "problems#feed", as: :feed

  get '/problems/:id/log', to: 'problems#log', as: :problem_log
  resources :images, only: [:create, :destroy]
  put '/vote', to: 'users#vote', as: :vote

  post '/problems/:id/bookmark', to: 'problems#bookmark', as: :problem_bookmark
	delete '/problems/:id/unbookmark', to: 'problems#unbookmark', as: :problem_unbookmark

  post '/topics/:id/follow', to: 'topics#follow', as: :topic_follow
	delete '/topics/:id/unfollow', to: 'topics#unfollow', as: :topic_unfollow

  resources :conversations do
    resources :messages
  end

  post '/conversations/:id/mark_as_read', to: 'conversations#mark_as_read', as: :mark_as_read_message
  post '/conversations/mark_all_as_read', to: 'conversations#mark_all_as_read', as: :mark_all_as_read_messages
 
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end

  get '/search', to: "search#search", as: :search

  get '/main_search', to: 'users#main_search', as: :main_search
  mathjax 'mathjax'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reportable, polymorphic: true
  belongs_to :user

  has_many :flag_reports, dependent: :destroy
  has_many :flags, through: :flag_reports

  #validates_uniqueness_of :user_id, scope: [:reportable_type, :reportable_id]
  validate :only_one_active
  validates :status, presence: true, 
                     inclusion: { in: ["pending", "declined", "closed",
                                        "in review"] }
  validates :details, length: { maximum: 2500 }
  validates :reportable_id, presence: true

  validates :reason, length: { maximum: 500 }

  scope :active, -> { where(expired_on: nil) }
  scope :pending, -> { where(status: 'pending') }

  def add_flags(flag_ids)
    flag_ids.each do |flag_id|
      flag = Flag.find(flag_id)
      FlagReport.create(report: self, flag: flag)
    end
  end

  def self.handle(post)
    if Report.automatic_deletion? post
      allowed_flags = (post.class.name == "Comment" ? 3 : 6)
      post.take_down("community", "#{post.class.name.downcase} was flagged as spam and/or offensive #{allowed_flags} or more times, and had a voting score of 0 or less")
    end
  end
 
  private

    def self.automatic_deletion?(post)
      if post.class.name == "Comment"
        if post.reports.count >= 3 and post.cached_votes_score <= 0
          return true
        end
      elsif %w(Problem Proof).include? post.class.name
        if post.reports.joins(:flag_reports).where(flag_reports: {flag_id: [1, 2]}).count >= 6 and post.cached_votes_score <= 0
          return true
        end
      end
      return false
    end

    def only_one_active
      if expired_on.nil? and !Report.find_by(user_id: user.id, reportable_type: reportable_type, 
                        reportable_id: reportable_id, expired_on: nil).nil?
        errors.add(:base, "should only have one active report")
      end
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_reputation_for_reports, only: [:new, :create, :update]
  before_action :correct_report, only: [:update]
  before_action :reviewer_priviliges, only: [:index, :help, :users, :claimed,
                                             :history, :show, :close, :decline,
                                             :reserve, :reserved, :unreserve]


  def show
    @report = Report.find(params[:id])
    if not params[:tab].nil?
      @tab = params[:tab]
    end
  end

  def new
    reportable_klass = params[:reportable_type].camelize.constantize
    @reportable = reportable_klass.find(params[:reportable_id])
  end

  def create
    @flag_error = Flag.validate_flags params[:report][:flags], params[:report][:reason]
    if @flag_error.empty?
      @report = Report.new(report_params)
      @report.user = current_user
      @report.status = "pending"
      @report.save
      @report.add_flags params[:report][:flags]
      PostHandler::HandlePost.new(post: @report.reportable, handle: :all).call
      if @report.reportable_type == "Problem" and @report.reportable.soft_deleted?
        flash[:notice] = "#{@report.reportable.user.username}'s #{@report.reportable_type.downcase} has been reported and deleted due to a substantial amount of negative feedback from the community."
        redirect_to root_url
      end
      #Report.handle(@report.reportable)
    end
  end

  def update
    @report = Report.find(params[:id])
    @report.update(status: "closed", expired_on: Time.now, details: "Report was closed by the reporter.")
  end

  def index
    @reports = Report.all.active
  end

  def close
  end

  def decline
  end

  def reserve
    @report = Report.find(params[:id])
    current_user.reserve @report
  end

  def unreserve
    @report = Report.find(params[:id])
    current_user.unreserve @report
  end
  
  def help
  end

  def reserved
    @reports = current_user.saved_reports
  end

  def users
  end

  def history
  end

  private

    def report_params
      params.require(:report).permit(:reportable_type, :reportable_id, :reason)
    end

    def correct_reputation_for_reports
      if current_user.reputation < 750
        flash[:alert] = "Action not authorized"
        redirect_to root_url
      end
    end

    def correct_report
      @report = Report.find(params[:id])
      if @report.user != current_user
        flash[:alert] = "Action not authorized"
        redirect_to root_url
      end
    end

    def reviewer_priviliges
      if !current_user.has_review_priviliges?
        flash[:alert] = "Action not authorized"
        redirect_to root_url
      end
    end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def flags_list(reportable)
    names = ["spam", "offensive", "very low quality"]
    if reportable.class.name == "Problem"
      names << "duplicate" 
      names << "not a proof problem"
    elsif reportable.class.name == "Proof"
      names << "not a proof"
    end
    names << "other"
    return Flag.where(name: names)
  end

  def report_button(model, options={})
    if signed_in?
      if current_user != model.user
        if model.class.name == "Problem" or model.class.name == 'Proof'
          html = "<a class='reportModalToggle greyLink headerFont float-right mr-18' data-remote='true' href='/reports/new?reportable_id=#{model.id}&amp;reportable_type=#{model.class.name}' title='Report'><i class='fa fa-flag-o mr-5'></i></a>"
        else
          html = "<span class='dot-sep'>·</span> <a class='reportModalToggle greyLink headerFont' data-remote='true' href='/reports/new?reportable_id=#{model.id}&amp;reportable_type=#{model.class.name}'><i class='fa fa-flag-o mr-5'></i>Report</a>"
        end
        html.html_safe
      end
    end
  end

  def reported_type_icon(type)
    return "<span class='fa fa-question ft-material-span'></span>".html_safe if type == "Problem"
    return "<span class='fa fa-comment ft-material-span'></span>".html_safe if type == "Comment"
    if type == "Proof"
      return "<span class='ft-material-span'><img class='inline-icon' src='/assets/proof_icon3.png'></img></span>".html_safe
    end
  end

  def reported_path(report)
    if report.reportable_type == "Problem"
      "/problems/#{report.reportable.id}"
    elsif report.reportable_type == "Topic"
      "/topics/#{report.reportable.id}"
    elsif report.reportable_type == "Comment"
      "/problems/#{report.reportable.get_problem.id}"
    elsif report.reportable_type == "Proof"
      "/problems/#{report.reportable.problem.id}"
    end
  end

  def reporter_link(report)
    "<a href='#{user_path(report.user.id)}' class='main-link'>#{report.user.username}</a>".html_safe
  end

  def reported_user_link(report)
    user = report.reportable.user
    "<a href='#{user_path(user.id)}' class='main-link'>#{user.username}'s</a>".html_safe
  end

  def reported_resource_title(report)
    msg = report.reportable_type
    if report.reportable_type == "Problem"
      msg = "#{report.reportable_type}"
      msg +=": <a href='#{problem_path(report.reportable.id)}' class='main-link'>#{report.reportable.title}</a>"
    elsif report.reportable_type == "Proof"
      msg = "<a href='#{problem_path(report.reportable.problem.id)}' class='main-link'>#{report.reportable_type}</a>"
      msg += " for problem <a href='#{problem_path(report.reportable.problem.id)}' class='main-link'>#{report.reportable.problem.title}</a>"
    elsif report.reportable_type == "Comment"
      msg = "<a href='#{problem_path(report.reportable.get_problem.id)}' class='main-link'>#{report.reportable_type}</a>"
      if report.reportable.commented_on_type == "Proof"
        msg += " on a proof for problem <a href='#{problem_path(report.reportable.get_problem.id)}' class='main-link'>#{report.reportable.get_problem.title}</a>"
      else
        msg += " on problem <a href='#{problem_path(report.reportable.get_problem.id)}' class='main-link'>#{report.reportable.get_problem.title}</a>"
      end
    end
    return msg.html_safe
  end

  def report_resource_message(report)
    resource = report.reportable
    resource_type = report.reportable_type
    if resource_type == "Problem"
      msg = "#{resource.title}"
    elsif resource_type == "Proof"
      msg = "Proof for problem: <i>#{resource.problem.title}</i>"
    elsif resource_type == "Comment"
      if resource.commented_on_type == "Problem"
        msg = "Comment on problem: <i>#{resource.get_problem.title}</i>"
      elsif resource.commented_on_type == "Proof"
        msg = "Comment on a proof for problem: <i>#{resource.get_problem.title}</i>"
      end
    end
    return msg.html_safe
  end

  def reserve_title(report)
    current_user.reserved?(report) ? 'Unreserve report' : 'Reserve report'
  end

  def reserve_class(report)
    return 'reserved' if current_user.reserved? report
  end
end

app/views/reports/_close_report_form.html.erb
<div class='form-group' style='margin-top: 20px;'>
  <%= label_tag "This #{resource.class.name.downcase} has one or more pending reports. Would you like to close a report? *" %>
  <div class="radio">
    <label><input type="radio" name="optradio">Yes</label>
  </div> 

  <div class="radio">
    <label><input type="radio" name="optradio">No</label>
  </div> 
</div>

app/views/reports/_more_info_report.html.erb
<div id="report-info-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/reports/_more_info_report_body.html.erb
  <section class='container ft-centered section'>
    <div class='row'>
      <div class='col-md-4 col-sm-6 mb-sm-50 ft-item ft-material'>
			  <%= link_to user_path(report.user.id) do %>
        <span class='ft-material-span' style="background-image: url('<%=avatar_src(report.user.id)%>'); background-size: cover;"></span>
	  	  <h5>Reporter</h5>
			  <p>
				  <span class='font-weight-600' style="font-size: 1.1em;">
				    <%= report.user.username%>
				  </span>
					<span class="label" style="margin-left: 5px; font-weight: 600; background: <%= reputation_color report.user.reputation %>;"><i class="mr-5 fa fa-trophy"></i><%= report.user.reputation%></span>
        </p>
				<% end %>
			</div>

		  <div class="col-md-4 col-sm-6 mb-sm-50 ft-item ft-material">
		    <%= reported_type_icon(report.reportable_type) %>
	      <h5>Reported</h5>
			  <p style='font-size: 1.1em; font-weight: 600;'><%=reported_resource_title(report)%></p>
			</div>

			<div class="col-md-4 col-sm-6 mb-sm-50 ft-item ft-material">
			  <%= link_to user_path(report.reportable.user.id) do %>
			  <span class='ft-material-span' style="background-image: url('<%=avatar_src(report.reportable.user.id)%>'); background-size: cover;"></span>
			  <h5><%=report.reportable_type%> Creator</h5>
			  <p>
				  <span class='font-weight-600' style="font-size: 1.1em;">
				    <%= report.reportable.user.username%>
				  </span>
					<span class="label" style="margin-left: 5px; font-weight: 600; background: <%= reputation_color report.reportable.user.reputation %>;"><i class="mr-5 fa fa-trophy"></i><%= report.reportable.user.reputation%></span>
        </p>
				<% end %>
		  </div>
		</div>
	</section>	

  <div class="bg-overlay">
	  <div class="cta-wrapper">
		  <div class="post-date font-weight-500">
			  <h3 class="no-transform">
				  <%= meta_data_icon report %>
				  <%=report.created_at.strftime('%B %d, %Y')%>
			  </h3>
		  </div>
		  <span class="colored-label <%=report.status.downcase.parameterize%> label-large"><%= report.status %></span>
		</div>
	</div>


  <section class="container section ft-steps-numbers">
	  <h2 style="margin-bottom: 40px; text-align: center;">Flags</h2>
	  <div class="row">
		  <% report.flags.each_with_index do |flag, index| %>
		    <!-- Flag  <%= index + 1 %> -->
			  <div class="col-lg-4 col-md-6 mb-sm-100 ft-item">
		      <span class="ft-nbr">0<%=index + 1%></span>
				  <h4><%=flag.name%></h4>
			    <p><%=flag.description%></p>
			  </div>
		  <% end %>
		</div><!-- / .row -->
	</section>

app/views/reports/_more_info_report_content.html.erb
<div class="modal-header">
  <button type="button" class="close ml-10" data-dismiss="modal">&times;</button>
	<h2 class="modal-title"><i class='fa fa-info-circle' title="More Information" aria-hidden="true"></i>&nbsp; More Info</h2>
</div>

<ul class="nav nav-tabs nav-tabs-line" role="tablist">
	<li class="nav-item active" role="presentation"><a class="nav-link" data-toggle="tab" href="<%=report_path(id: report.id, tab: 'report')%>" aria-controls="exampleLine1" role="tab" data-remote='true' aria-selected="true">Report Info</a></li>
	<li class="nav-item" role="presentation"><a class="nav-link" id='reportable-info-link' data-toggle="tab" href="<%=report_path(id: report.id, tab: 'resource')%>" data-remote='true' aria-controls="exampleLine2" role="tab" aria-selected="false"><%=report.reportable_type%> Info</a></li>
</ul>
<div class='modal-body' id='report-info-modal-body'>
  <%= render(:partial => '/reports/more_info_report_body', locals:  {report: report} ) %>
</div>
<div class="modal-footer">
  <div class='report-actions'>
	  <%= link_to send("edit_" + report.reportable_type.downcase + "_path", report.reportable.id), class: 'get-action' do %>

	    <span class="fa fa-pencil mr-5" title="Edit <%=report.reportable_type%>"></span>
    <% end %>

		<%= link_to '#', class: 'success-action', title: "Close" do %>
		  <span class='fa fa-check-circle-o mr-5'></span>
	  <% end %>

    <a data-remote="true" class='put-action' rel="nofollow" data-method="put" href="/reports/1/reserve">
	    <span class="fa fa-bookmark-o mr-5" title="Reserve Report"></span>
    </a>

    <%= link_to '#', class: 'warning-action', title:"Send #{report.reportable_type} to Review Queue" do %>
		  <span class='fa fa-paper-plane mr-5'></span>
		<% end %>

		<a data-remote="true" class='danger-action' rel="nofollow" data-method="put" href="/reports/1/decline">
		  <span class="fa fa-ban mr-5" title="Decline Report"></span>
		</a>
	</div>
  <%= link_to '#' do %>
    <button type="button" class="btn btn-xs small-padding">View <%=report.reportable_type%></button>
  <% end %>
</div>

app/views/reports/_more_info_resource_body.html.erb
<div class="blog-post activity_item mb-40" style='padding: 20px 60px 20px 60px;'> 
  <div class="bp-content">
    <div class="post-meta" style='padding-left: 0; padding-right: 0;'>
      <div class="post-date float-left font-weight-500">
        <span class="no-transform"> 
          <%= meta_data_icon report.reportable %>
          <%=report.reportable.created_at.strftime('%B %d, %Y')%>
        </span>
      </div>
      <div class="clearfix"></div>
    </div><!-- / .meta -->
    <div class='clearfix'</div>
    <!-- Post Title -->
    <div class: "post-title pa-0">
      <h2 class="problem-desc pb-15 mt-10"><%=report_resource_message(report) %></h2>
    </div>


    <div class="row mt-20">
      <div class="col-md-12 blog-post-comments proofs-section">
       <!-- Comment 1 --> 
        <div class="bp-comment"> 
          <div class="author-container">
            <div class="author-img">
              <a href="<%= user_path(report.reportable.user) %>"><img width="60" height="60" src="<%=avatar_src(report.user.id)%>" alt=""></a>
            </div>

            <h6><a href="<%= user_path(report.reportable.user) %>"><%= report.reportable.user.username %></a></h6>
			      <span class="label" style="margin-left: 5px; font-weight: 600; background: <%= reputation_color report.reportable.user.reputation %>;"><i class="mr-5 fa fa-trophy"></i><%= report.reportable.user.reputation%></span>
          </div>
          <br>

          <div class="comment-content">
            <%= sanitize report.reportable.content %>
          </div>
          <br>
          <div class="clearfix"></div>

          <% if report.reportable_type == "Problem" %>
            <span class="problem-comment problem-info"><i class="glyphicon glyphicon-user mr-5"></i> <span id="problem-<%=report.reportable.id%>-followers"><%= pluralize(report.reportable.followers.count, "Follower") %></span></span>
            <span class="problem-comment problem-info"><i class="glyphicon glyphicon-comment mr-5"></i><%= pluralize(report.reportable.proofs.count, "Proof") %></span>
            <span class="problem-comment problem-info"><i class="glyphicon glyphicon-eye-open mr-5"></i><%=pluralize(report.reportable.impressionist_count, "view")%></span>
            <span class="problem-comment problem-info"><i class="glyphicon glyphicon-pencil mr-5"></i> <%=pluralize(report.reportable.versions.count, "Edit")%></span>
          <% elsif report.reportable_type == "Proof" %>
            <span class="problem-comment problem-info"><i class="glyphicon glyphicon-comment mr-5"></i><%= pluralize(report.reportable.comments.count, "Comment") %></span>
            <span class="problem-comment problem-info"><i class="glyphicon glyphicon-pencil mr-5"></i> <%=pluralize(report.reportable.versions.count, "Edit")%></span>
          <% elsif report.reportable_type == "Comment" %>
          
          <% end %>

          <span class="problem-comment problem-info"><i class="glyphicon glyphicon-thumbs-up mr-5"></i><%= pluralize(report.reportable.cached_votes_up, "Upvote") %></span>
          <span class="problem-comment problem-info"><i class="glyphicon glyphicon-thumbs-down mr-5"></i><%=pluralize(report.reportable.cached_votes_down, "Downvote")%></span>
          <span class="problem-view problem-info"><i class="glyphicon glyphicon-heart mr-5"></i> <%= "#{report.reportable.cached_votes_score} Score" %></span>
        </div><!-- / .bp-comment -->        
      </div><!-- / .blog-post-comments -->
    </div><!-- / .row --> 
  </div>
</div>

app/views/reports/_report_modal.html.erb
<div id="reportModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="reportModalClose" data-dismiss="modal"></div> 
      <div class="modal-body">
        <h2 class="modal-title headerFont darkType fontWeight-600 fontSize-24"></h2>
        <div class="modal-substance">

        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_reports_table.html.erb
<!-- Table Hover -->
<div class="col-lg-12 ws-m">
	<div class="table-responsive">        
		<table class="table table-hover">
			<thead>
				<tr>
					<th style="width: 6%; text-align: center;">Reporter</th>
					<th class='th-type'>Reported Type</th>
					<th class='th-date'>Date</th>
					<th class="th-flags">Flags</th>
					<th class="th-status">Status</th>
					<th class='th-view'>View</th>
					<th class='th-actions'>Actions</th>
					<th class='th-more-info'>More Info</th>
				</tr>
			</thead>
			<tbody>
				<% @reports.each do |report| %>
					<tr>
						<td style="text-align: center; padding-left: 0; padding-right: 0;">
							<%= link_to user_path(report.user) do %>
								<img class="img-circle" alt="40x40" style="width: 40px; height: 40px;" src="<%= avatar_src(report.user.id) %>" title="<%=report.user.username%>" data-holder-rendered="true">
								<% end %>
						</td>
						<td class='td-type'><span class='ml-20'><%= report.reportable_type %></span></td>
						<td class='td-date'>
							<%= time_ago_in_words(report.created_at) %> ago
						</td>
						<td class="td-flags" style="white-space: normal;">
							<% report.flags.each do |flag| %>
								<span class='colored-label'><%=flag.name%></span>

							<% end %>
						</td>
						<td class="td-status">
							<span class='colored-label <%= report.status.downcase.parameterize %>'><%=report.status%></span>
						</td>
						<td class='td-view'>
							<%= link_to "#{reported_path(report)}" do %>
								<button class="btn btn-ghost btn-xs small-padding">View <%= report.reportable_type %></button>
							<% end %>
						</td>
						<td class='td-actions'>
							<div class='secondary-dropdown'>
								<span class='fa fa-ellipsis-h mr-5 secondary-dropdown-toggle' title="actions"></span>
								<div id="report-actions-<%=report.id%>" class="secondary-dropdown-content">
                  <% if report.reportable_type != 'Comment' %>
									  <%= link_to send("edit_" + report.reportable_type.downcase + "_path", report.reportable.id) do %>
										  <span class='fa fa-pencil mr-5'></span>Edit
									  <% end %>
                  <% end %>
									<a href="#"><span class='fa fa-check-circle-o mr-5'></span>Close</a>
									<a href="#"><span class='fa fa-paper-plane mr-5'></span>Send <%= report.reportable_type %> to Review Queue</a>
								</div>
							</div>

							<%= link_to reserve_report_path(report.id), id: "report-reserve-#{report.id}", remote: true, method: :put do %>
								<span class='fa fa-bookmark-o mr-5 <%= reserve_class(report) %>' title="<%=reserve_title(report)%>"></span>
							<% end %>

							<%= link_to decline_report_path(report.id), remote: true, method: :put do %>
								<span class='fa fa-ban mr-5' title="Decline Report"></span>
							<% end %>

						</td>
						<td class='td-more-info'>
							<%= link_to report_path(report.id), remote: true do %>
								<span class='fa fa-info mr-5' title="More Information"></span>
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table><!-- / .table -->
	</div>
</div><!-- / .col-lg-8 -->

app/views/reports/new.js.erb
<% if !Report.exists?(user_id: current_user.id, reportable_id: @reportable.id, reportable_type: @reportable.class.name, expired_on: nil) %>
  $('#reportModal .modal-title').html("I am reporting this <%= @reportable.class.name.downcase %> as...");
  $('#reportModal .modal-body .modal-substance').html("<%= escape_javascript render(:partial => '/reports/new', locals:  {reportable: @reportable }) %>");
<% else %>
  <% report = Report.find_by(user_id: current_user.id, reportable_id: @reportable.id, reportable_type: @reportable.class.name) %>
  $('#reportModal .modal-title').html("You already have a pending report on this <%= @reportable.class.name.downcase %> for the following...");

  $('#reportModal .modal-body .modal-substance').html("<%= escape_javascript render(:partial => '/reports/edit', locals:  {:@flags => report.flags, :@report => report }) %>");
<% end %>

app/views/reports/reserve.js.erb
$('#report-reserve-<%=@report.id%>').attr('data-method', 'delete');
$('#report-reserve-<%=@report.id%>').attr('href', '<%=unreserve_report_path(@report.id)%>');
$('#report-reserve-<%=@report.id%> .fa-bookmark-o').addClass('reserved');
$('#report-reserve-<%=@report.id%> .fa-bookmark-o').attr('title', 'Unreserve report');

app/views/reports/reserved.js.erb
$('.tab-content .page-content .boxedtitle h2').text('Reserved Reports');
$('.tab-content .tab-pane .tab-list-content').html("<%= escape_javascript render(:partial => '/reports/reports_table', local:  { :@reports => @reports } ) %>");

app/views/reports/unreserve.js.erb
$('#report-reserve-<%=@report.id%>').attr('data-method', 'put');
$('#report-reserve-<%=@report.id%>').attr('href', '<%=reserve_report_path(@report.id)%>');
$('#report-reserve-<%=@report.id%> .fa-bookmark-o').removeClass('reserved');
$('#report-reserve-<%=@report.id%> .fa-bookmark-o').attr('title', 'Reserve report');